# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Code, Learn, Repeat
repository: fsferrara/fsferrara.github.io
author: Saverio Ferrara
# email: fsferrara@users.noreply.github.com
description: >- # this means to ignore newlines until "baseurl:"
  Being a follower isn't so bad.
baseurl: "" # the subpath of your site, e.g. /blog
domain: "fsferrara.github.io"
url: "https://fsferrara.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  fsferrara
linkedin_username: fsferrara
# twitter_username: fsferrara
# dribbble_username: fsferrara
# facebook_username: fsferrara
# flickr_username: fsferrara
# instagram_username: fsferrara
# pinterest_username: fsferrara
# youtube_username: fsferrara
# googleplus_username: +fsferrara

# rss: rss
show_excerpts: false # set to true to show excerpts on the homepage

# Build settings
markdown: kramdown
theme: minima
minima:
  dayless_date_format: "%B, %Y"
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

permalink: pretty

collections:
  work:
    output: true
    sort_by: date
    permalink: /:collection/:path/
  resume:
    output: true
    sort_by: date
    permalink: /:collection/:path/

defaults:
  - scope:
      path: ""
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "work"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "resume"
    values:
      layout: "page"

# Menu settings
header_pages:
  - about.md
  - resume.md
  - work.md
  - contact.md

# Every file or directory beginning with the following characters: ., _ , # or ~ in
# the source directory will not be included in the destination folder.
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
# Include in processing.
include:
  - _pages

# Exclude from processing.
exclude:
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE
  - README.md
  - Makefile
